import assert from 'node:assert/strict';
import { readFileSync } from 'node:fs';
import { describe, it } from 'node:test';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '../..');
const css = readFileSync(path.join(root, 'public/css/app.css'), 'utf8');
const html = readFileSync(path.join(root, 'public/index.html'), 'utf8');
const view = readFileSync(path.join(root, 'public/js/views/home.js'), 'utf8');
const shell = readFileSync(path.join(root, 'public/js/shell.js'), 'utf8');
const i18n = readFileSync(path.join(root, 'public/js/i18n.js'), 'utf8');

describe('home brand-blue theme', () => {
  it('keeps home action bindings and the split dashboard markup', () => {
    assert.match(view, /data-home-action=/);
    assert.match(view, /data-home-logo-toggle/);
    assert.match(view, /data-home-logo-menu/);
    assert.match(view, /data-home-launcher/);
    assert.match(view, /tabindex=/);
    assert.doesNotMatch(view, /data-home-menu-close/);
    assert.doesNotMatch(view, /trigger-hint|closeButtonHtml/);
    assert.match(view, /data-home-path=/);
    assert.match(view, /key: 'create'/);
    assert.match(view, /key: 'pending'/);
    assert.match(view, /key: 'vehicles'/);
    assert.match(view, /key: 'diagnostics'/);
    assert.match(view, /key: 'inventory'/);
    assert.match(view, /key: 'urgencias'/);
    // Soporte is gone from the owner-facing app, launcher included.
    assert.doesNotMatch(view, /data-home-support=|key: 'support'|openPlatformSupport/);
    assert.match(view, /openNewBookingSheet/);
    assert.match(view, /navigate\('\/appointments\?filter=today'\)/);
    assert.match(view, /navigate\(path\)/);
    assert.match(view, /classList\.toggle\('app--home', active\)/);
    assert.match(view, /classList\.toggle\('header--home', active\)/);
    assert.match(view, /classList\.toggle\('nav--home', active\)/);
    assert.match(view, /home-split__trigger-mark/);
    assert.match(view, /_homeMenuOpen/);
    assert.match(view, /writeMenuOpen\(false\)/);
    assert.match(view, /setLauncherOpen\(root, false\)/);
    assert.match(view, /addEventListener\('pointerdown', closeIfOutside, true\)/);
    assert.match(view, /closest\('\[data-home-logo-toggle\], \[data-home-logo-menu\]'\)/);
    assert.match(view, /setLauncherOpen\(root, !readMenuOpen\(\)\)/);
    assert.match(view, /pointerEvents = 'none'/);
    assert.match(view, /removeProperty\('pointer-events'\)/);
    assert.match(view, /setAttribute\('inert'/);
    assert.match(view, /removeAttribute\('inert'\)/);
    assert.match(view, /clearTriggerSpin/);
    assert.match(view, /is-spinning/);
    assert.match(view, /home-split__kpi/);
    assert.match(view, /home.trustTagline/);
    assert.match(i18n, /'home\.trustTagline':\s*'TODO EN UNO 🛠️'/);
    assert.doesNotMatch(i18n, /TU TALLER DE CONFIANZA/);
    assert.doesNotMatch(i18n, /YOUR TRUSTED SHOP/);
    assert.match(view, /headingHtml/);
    assert.doesNotMatch(view, /menu-kicker|todoTitleHtml|dropdownTitle/);
    assert.match(view, /logo-mark\.svg/);
    assert.match(view, /home-split__tile-icon--alert/);
    assert.match(shell, /nav__item--urgencias/);
  });

  it('paints Inicio over a workshop photo with a readable white overlay', () => {
    // Only the cache-busting matters here; pinning the literal revision made
    // this assertion fail on every unrelated stylesheet change.
    assert.match(html, /app\.css\?v=[\w-]+/);
    assert.match(css, /--home-brand:\s*#0ea5e9/);
    assert.match(css, /\.app--home\s*\{[^}]*background:\s*#f8f9fa/s);
    assert.match(css, /\.home-split\s*\{[^}]*home-workshop\.jpg/s);
    assert.match(css, /\.home-split::before\s*\{[^}]*rgba\(255,\s*255,\s*255,\s*0\.4\)/s);
    assert.doesNotMatch(css, /--home-cobalt:\s*#0047ab/);
    assert.match(css, /\.home-split__shop\s*\{[^}]*color:\s*#0f172a/s);
    assert.match(css, /\.home-split__shop\s*\{[^}]*font-weight:\s*800/s);
    assert.match(css, /\.home-split__shop\s*\{[^}]*font-size:\s*30px/s);
    assert.match(css, /\.home-split__shop\s*\{[^}]*drop-shadow/s);
    assert.match(css, /\.home-split__tagline\s*\{[^}]*color:\s*#0ea5e9/s);
    assert.match(css, /\.home-split__tagline\s*\{[^}]*font-weight:\s*700/s);
    assert.match(css, /\.home-split__tagline\s*\{[^}]*-webkit-text-stroke:\s*1px #ffffff/s);
    assert.match(css, /\.home-split__tagline\s*\{[^}]*paint-order:\s*stroke fill/s);
    assert.match(css, /\.home-split__tile-icon\s*\{[^}]*color:\s*var\(--home-brand\)/s);
    assert.match(css, /\.home-split__tile-icon--alert\s*\{[^}]*color:\s*#ef4444/s);
    assert.match(css, /\.home-split__trigger\s*\{[^}]*border-radius:\s*24px/s);
    assert.match(css, /\.home-split__trigger\s*\{[^}]*#22d3ee/s);
    assert.match(css, /\.home-split__trigger\s*\{[^}]*#06b6d4/s);
    assert.match(css, /\.home-split__trigger\s*\{[^}]*linear-gradient/s);
    assert.match(css, /\.home-launcher\s*\{[^}]*margin:\s*0 0 48px/s);
    assert.match(css, /\.home-split__trigger-mark\s*\{[^}]*invert\(1\)/s);
    assert.match(css, /@keyframes home-mark-spin/);
    assert.match(css, /\.home-launcher\.is-open \.home-split__rail\s*\{[^}]*opacity:\s*1/s);
    assert.match(css, /\.home-split__trigger-mark\.is-spinning\s*\{[^}]*animation:\s*home-mark-spin 0\.3s ease-in-out 1/s);
    assert.doesNotMatch(css, /\.home-split__trigger-mark\.is-spinning\s*\{[^}]*infinite/s);
    assert.match(css, /\.home-split__rail\s*\{[^}]*pointer-events:\s*none/s);
    assert.match(css, /\.home-launcher\.is-open \.home-split__rail\s*\{[^}]*pointer-events:\s*auto/s);
    assert.match(css, /\.home-split__rail\s*\{[^}]*visibility:\s*hidden/s);
    assert.doesNotMatch(css, /\.home-split__rail\s*\{[^}]*transition:\s*all/s);
    assert.match(css, /\.home-split__rail\s*\{[^}]*width 0\.3s ease-in-out/s);
    assert.match(css, /\.home-split__trigger\s*\{[^}]*pointer-events:\s*auto/s);
    assert.match(css, /\.home-split__rail \.home-split__tile-label\s*\{[^}]*font-size:\s*16px/s);
    assert.match(css, /\.home-split__rail \.home-split__tile-label\s*\{[^}]*color:\s*#1e293b/s);
    assert.match(css, /\.home-split__kpi\s*\{[^}]*border-radius:\s*16px/s);
    assert.match(css, /\.home-split__kpi\s*\{[^}]*flex-direction:\s*row/s);
    assert.match(css, /\.home-split__tile\s*\{[^}]*border-radius:\s*20px/s);
    assert.match(css, /--home-done:\s*#00c853/);
    assert.match(css, /--home-pending:\s*#ff6d00/);
    assert.match(css, /@keyframes home-metric-glow/);
    assert.match(css, /\.nav--home \.nav__item\s*\{[^}]*color:\s*#0ea5e9/s);
    assert.match(css, /\.nav__item--urgencias,\s*\n\.nav--home \.nav__item--urgencias[\s\S]*color:\s*#ef4444/);
    assert.match(css, /\.nav__item--urgencias\[aria-current='page'\][\s\S]*color:\s*#dc2626/);
    assert.match(css, /\.nav__item--urgencias\[aria-current='page'\]::before[\s\S]*background:\s*#fef2f2/);
    assert.match(css, /\.header__wordmark\s*\{[^}]*color:\s*var\(--brand\)/s);
  });
});
