import assert from 'node:assert/strict';
import { readFileSync } from 'node:fs';
import { describe, it } from 'node:test';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '../..');
const css = readFileSync(path.join(root, 'public/css/app.css'), 'utf8');
const html = readFileSync(path.join(root, 'public/index.html'), 'utf8');
const view = readFileSync(path.join(root, 'public/js/views/home.js'), 'utf8');
const shell = readFileSync(path.join(root, 'public/js/shell.js'), 'utf8');
const i18n = readFileSync(path.join(root, 'public/js/i18n.js'), 'utf8');

describe('home brand-blue theme', () => {
  it('keeps home action bindings and the split dashboard markup', () => {
    assert.match(view, /data-home-action=/);
    assert.match(view, /data-home-logo-toggle/);
    assert.match(view, /data-home-logo-menu/);
    assert.match(view, /data-home-launcher/);
    assert.match(view, /tabindex=/);
    assert.doesNotMatch(view, /data-home-menu-close/);
    assert.doesNotMatch(view, /trigger-hint|closeButtonHtml/);
    assert.match(view, /data-home-path=/);
    assert.match(view, /key: 'create'/);
    assert.match(view, /key: 'pending'/);
    assert.match(view, /key: 'vehicles'/);
    assert.match(view, /key: 'diagnostics'/);
    assert.match(view, /key: 'inventory'/);
    assert.match(view, /key: 'urgencias'/);
    // Soporte is gone from the owner-facing app, launcher included.
    assert.doesNotMatch(view, /data-home-support=|key: 'support'|openPlatformSupport/);
    assert.match(view, /openNewBookingSheet/);
    assert.match(view, /navigate\('\/appointments\?filter=today'\)/);
    assert.match(view, /navigate\(path\)/);
    assert.match(view, /classList\.toggle\('app--home', active\)/);
    assert.match(view, /classList\.toggle\('header--home', active\)/);
    assert.match(view, /classList\.toggle\('nav--home', active\)/);
    assert.match(view, /home-split__trigger-mark/);
    assert.match(view, /_homeMenuOpen/);
    assert.match(view, /writeMenuOpen\(false\)/);
    assert.match(view, /setLauncherOpen\(root, false\)/);
    assert.match(view, /addEventListener\('click', closeIfOutside/);
    assert.match(view, /eventHitsSelector/);
    assert.match(view, /placeRail/);
    assert.match(view, /clearRailPosition\(menu\)/);
    assert.match(view, /setLauncherOpen\(root, next\)/);
    assert.match(view, /pointerEvents = 'none'/);
    assert.match(view, /removeProperty\('pointer-events'\)/);
    assert.match(view, /setAttribute\('inert'/);
    assert.match(view, /removeAttribute\('inert'\)/);
    assert.match(view, /clearTriggerSpin/);
    assert.match(view, /flipTrigger/);
    assert.match(view, /FAB_MOVE_MS = 350/);
    assert.match(view, /FAB_SPIN_MS = 500/);
    assert.match(view, /swapTriggerGlyph/);
    assert.match(view, /clearTriggerSpin\(swap, \{ restart: true \}\)/);
    assert.match(
      view,
      /toggle\.classList\.toggle\('is-tool', showWrench\);\s*clearTriggerSpin\(swap\);/
    );
    assert.match(view, /is-tool/);
    assert.match(view, /home-split__trigger-wrench/);
    assert.match(view, /icon\('wrench'/);
    assert.match(view, /FAB_EASE = 'cubic-bezier\(0\.16, 1, 0\.3, 1\)'/);
    assert.match(view, /armHomeMotion/);
    assert.match(view, /classList\.add\('is-ready'\)/);
    assert.match(view, /requestAnimationFrame/);
    assert.match(view, /toggle\.getBoundingClientRect\(\)/);
    assert.doesNotMatch(view, /menu\.getBoundingClientRect\(\)/);
    assert.match(view, /is-spinning/);
    assert.match(view, /home-split__kpi/);
    assert.match(view, /home.trustTagline/);
    assert.match(i18n, /'home\.trustTagline':\s*'TODO EN UNO 🛠️'/);
    assert.doesNotMatch(i18n, /TU TALLER DE CONFIANZA/);
    assert.doesNotMatch(i18n, /YOUR TRUSTED SHOP/);
    assert.match(view, /headingHtml/);
    assert.doesNotMatch(view, /menu-kicker|todoTitleHtml|dropdownTitle/);
    assert.match(view, /brandMarkSvg/);
    assert.match(view, /logo-mark\.svg/);
    assert.match(view, /home-split__tile--urgencias/);
    assert.match(view, /home-split__tile--diagnostics/);
    assert.match(view, /home-split__tile--pending/);
    assert.match(view, /function tileToneClass/);
    assert.match(view, /home-split__tile-icon--alert/);
    assert.match(shell, /nav__item--urgencias/);
  });

  it('paints Inicio over a workshop photo with a readable white overlay', () => {
    // Only the cache-busting matters here; pinning the literal revision made
    // this assertion fail on every unrelated stylesheet change.
    assert.match(html, /app\.css\?v=[\w-]+/);
    assert.match(css, /--home-brand:\s*#0ea5e9/);
    assert.match(css, /\.app--home\s*\{[^}]*background:\s*#f8f9fa/s);
    assert.match(css, /\.home-split\s*\{[^}]*home-workshop\.jpg/s);
    assert.match(css, /\.home-split::before\s*\{[^}]*rgba\(255,\s*255,\s*255,\s*0\.4\)/s);
    assert.doesNotMatch(css, /--home-cobalt:\s*#0047ab/);
    assert.match(css, /\.home-split__shop\s*\{[^}]*color:\s*#0f172a/s);
    assert.match(css, /\.home-split__shop\s*\{[^}]*font-weight:\s*800/s);
    assert.match(css, /\.home-split__shop\s*\{[^}]*font-size:\s*30px/s);
    assert.match(css, /\.home-split__shop\s*\{[^}]*drop-shadow/s);
    assert.match(css, /\.home-split__tagline\s*\{[^}]*color:\s*#0ea5e9/s);
    assert.match(css, /\.home-split__tagline\s*\{[^}]*font-weight:\s*700/s);
    assert.match(css, /\.home-split__tagline\s*\{[^}]*-webkit-text-stroke:\s*1px #ffffff/s);
    assert.match(css, /\.home-split__tagline\s*\{[^}]*paint-order:\s*stroke fill/s);
    assert.match(css, /\.home-split__tile-icon\s*\{[^}]*color:\s*var\(--home-brand\)/s);
    assert.match(css, /\.home-split__tile-icon--alert\s*\{[^}]*color:\s*#ef4444/s);
    assert.match(css, /\.home-split__trigger\s*\{[^}]*border-radius:\s*24px/s);
    assert.match(css, /\.home-split__trigger\s*\{[^}]*#22d3ee/s);
    assert.match(css, /\.home-split__trigger\s*\{[^}]*#06b6d4/s);
    assert.match(css, /\.home-split__trigger\s*\{[^}]*linear-gradient/s);
    assert.match(css, /\.home-launcher\s*\{[^}]*margin:\s*0 0 32px/s);
    assert.match(css, /\.home-split__trigger-swap\s*\{[^}]*will-change:\s*transform/s);
    assert.match(css, /\.home-split__trigger-swap\s*\{[^}]*backface-visibility:\s*hidden/s);
    assert.match(css, /@keyframes home-swap-spin/);
    assert.match(css, /@keyframes home-glyph-in/);
    assert.match(css, /@keyframes home-glyph-out/);
    assert.match(css, /\.home-launcher\.is-open \.home-split__rail[\s\S]*?\{[^}]*opacity:\s*1/s);
    assert.match(css, /\.home-launcher\.is-open \.home-split__rail[\s\S]*?\{[^}]*position:\s*relative/s);
    assert.match(css, /\.home-split__rail\s*\{[^}]*position:\s*absolute/s);
    assert.match(css, /\.home-split__rail\s*\{[^}]*width:\s*0/s);
    assert.match(css, /\.home-split__rail\s*\{[^}]*overflow:\s*hidden/s);
    assert.match(css, /\.home-launcher\s*\{[^}]*flex-direction:\s*row/s);
    assert.match(css, /\.home-launcher\.is-open\s*\{[^}]*flex-direction:\s*row-reverse/s);
    assert.match(css, /\.home-launcher\.is-open\s*\{[^}]*justify-content:\s*flex-start/s);
    assert.match(css, /\.home-launcher\.is-open\s*\{[^}]*gap:\s*12px/s);
    assert.match(css, /\.home-split\s*\{[^}]*--home-motion:\s*0\.35s/s);
    assert.match(css, /\.home-split\s*\{[^}]*--home-spin:\s*0\.5s/s);
    assert.match(css, /\.home-split\s*\{[^}]*--home-ease:\s*cubic-bezier\(0\.16, 1, 0\.3, 1\)/s);
    assert.match(css, /home-swap-spin var\(--home-spin\) var\(--home-ease\) 1/);
    assert.match(css, /@keyframes home-swap-spin[\s\S]*rotate\(180deg\)/);
    assert.match(css, /@keyframes home-glyph-in[\s\S]*50%,\s*100%/);
    assert.match(css, /\.home-split__trigger\.is-tool \.home-split__trigger-wrench[\s\S]*?opacity:\s*1/s);
    assert.match(css, /\.home-split__trigger-swap\s*\{[^}]*color:\s*#ffffff/s);
    assert.doesNotMatch(css, /\.home-split__trigger-swap\.is-spinning\s*\{[^}]*infinite/s);
    assert.doesNotMatch(css, /\.home-split__trigger-mark\s*\{[^}]*filter:/s);
    assert.match(css, /\.home-split__rail\s*\{[^}]*pointer-events:\s*none/s);
    assert.match(css, /\.home-launcher\.is-open \.home-split__rail[\s\S]*?\{[^}]*pointer-events:\s*auto/s);
    assert.match(css, /\.home-split__rail\s*\{[^}]*visibility:\s*hidden/s);
    assert.doesNotMatch(css, /\.home-split__rail\s*\{[^}]*transition:\s*all/s);
    assert.doesNotMatch(css, /\.home-split__rail\s*\{[^}]*width 0\.3s/);
    // Open rail sits left of the right-docked mark and eases in over 0.35s.
    assert.match(css, /\.home-split__rail\s*\{[^}]*transform:\s*translate3d\(0, 12px, 0\) scale\(0\.96\)/s);
    assert.match(css, /\.home-split__rail\s*\{[^}]*will-change:\s*transform, opacity/s);
    assert.match(css, /\.home-split__rail\s*\{[^}]*transform var\(--home-motion\) var\(--home-ease\)/s);
    assert.match(css, /\.home-launcher\.is-open \.home-split__rail[\s\S]*?transform:\s*translate3d\(0, 0, 0\) scale\(1\)/s);
    assert.match(css, /--home-neon-cyan:\s*rgba\(0, 243, 255, 0\.5\)/);
    assert.match(css, /--home-neon-orange:\s*rgba\(255, 128, 0, 0\.6\)/);
    assert.match(css, /--home-neon-green:\s*rgba\(0, 255, 128, 0\.6\)/);
    assert.match(css, /\.home-split__tile\s*\{[^}]*0 0 15px var\(--home-neon-cyan\)/s);
    assert.match(css, /\.home-split__tile--urgencias\s*\{[^}]*0 0 15px var\(--home-neon-red\)/s);
    assert.match(css, /\.home-split__tile--diagnostics\s*\{[^}]*0 0 15px var\(--home-neon-cobalt\)/s);
    assert.match(css, /\.home-split__tile--pending\s*\{[^}]*0 0 15px var\(--home-neon-orange\)/s);
    assert.match(css, /\.home-split__kpi--done\s*\{[^}]*0 0 15px var\(--home-neon-green\)/s);
    assert.match(css, /\.home-split__kpi--pending\s*\{[^}]*0 0 15px var\(--home-neon-orange\)/s);
    assert.match(css, /@keyframes home-tile-enter[\s\S]*translate3d\(0, 0, 0\) scale\(1\)/);
    assert.match(css, /\.home-split__tile\s*\{[^}]*will-change:\s*transform, opacity/s);
    assert.match(css, /\.home-split:not\(\.is-ready\)/s);
    assert.match(css, /@keyframes home-kpi-enter/);
    assert.match(css, /@keyframes home-tile-enter/);
    assert.match(css, /\.home-split__kpi--pending[\s\S]*animation-delay:\s*0\.16s/);
    assert.match(css, /\.home-split__trigger\s*\{[^}]*pointer-events:\s*auto/s);
    assert.match(css, /\.home-split__rail \.home-split__tile-label\s*\{[^}]*font-size:\s*16px/s);
    assert.match(css, /\.home-split__rail \.home-split__tile-label\s*\{[^}]*color:\s*#1e293b/s);
    assert.match(css, /\.home-split__kpi\s*\{[^}]*border-radius:\s*16px/s);
    assert.match(css, /\.home-split__kpi\s*\{[^}]*flex-direction:\s*row/s);
    assert.match(css, /\.home-split__tile\s*\{[^}]*border-radius:\s*20px/s);
    assert.match(css, /--home-done:\s*#00c853/);
    assert.match(css, /--home-pending:\s*#ff6d00/);
    assert.match(css, /\.home-split__metric-value\.is-glowing\s*\{[^}]*animation:\s*home-metric-glow/s);
    assert.match(css, /\.nav--home \.nav__item\s*\{[^}]*color:\s*#0ea5e9/s);
    assert.match(css, /\.nav__item--urgencias,\s*\n\.nav--home \.nav__item--urgencias[\s\S]*color:\s*#ef4444/);
    assert.match(css, /\.nav__item--urgencias\[aria-current='page'\][\s\S]*color:\s*#dc2626/);
    assert.match(css, /\.nav__item--urgencias\[aria-current='page'\]::before[\s\S]*background:\s*#fef2f2/);
    assert.match(css, /\.header__wordmark\s*\{[^}]*color:\s*var\(--brand\)/s);
  });

  it('keeps the six owner-nav icons in the image_2.png order', () => {
    const owner = shell.match(/const OWNER_NAV = \(\) => \[([\s\S]*?)\];/)[1];
    const keys = [...owner.matchAll(/key: '([^']+)'/g)].map((m) => m[1]);
    assert.deepEqual(keys, ['home', 'appointments', 'urgencias', 'vehicles', 'inventory', 'more']);
    assert.equal(keys.indexOf('urgencias'), 2);
    assert.equal(keys.indexOf('vehicles'), 3);
    assert.match(css, /\.nav\s*\{[^}]*grid-auto-columns:\s*minmax\(0, 1fr\)/s);
    assert.match(css, /\.nav\s*\{[^}]*overflow:\s*hidden/s);
    assert.match(css, /\.nav\s*\{[^}]*z-index:\s*45/s);
    assert.match(css, /\.nav__item\s*\{[^}]*min-width:\s*0/s);
    assert.doesNotMatch(css, /\.nav\s*\{[^}]*overflow-x:\s*auto/s);
  });
});
